/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as PdfsRouteImport } from './routes/pdfs'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as AdminGerarRouteImport } from './routes/admin_.gerar'
import { Route as AdminQuestoesRouteImport } from './routes/admin_.questoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfsRoute = PdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGerarRoute = AdminGerarRouteImport.update({
  id: '/admin_/gerar',
  path: '/admin/gerar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestoesRoute = AdminQuestoesRouteImport.update({
  id: '/admin_/questoes',
  path: '/admin/questoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/historico': typeof HistoricoRoute
  '/pdfs': typeof PdfsRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/suporte': typeof SuporteRoute
  '/admin/gerar': typeof AdminGerarRoute
  '/admin/questoes': typeof AdminQuestoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/historico': typeof HistoricoRoute
  '/pdfs': typeof PdfsRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/suporte': typeof SuporteRoute
  '/admin/gerar': typeof AdminGerarRoute
  '/admin/questoes': typeof AdminQuestoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/historico': typeof HistoricoRoute
  '/pdfs': typeof PdfsRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/suporte': typeof SuporteRoute
  '/admin_/gerar': typeof AdminGerarRoute
  '/admin_/questoes': typeof AdminQuestoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/historico'
    | '/pdfs'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/suporte'
    | '/admin/gerar'
    | '/admin/questoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/historico'
    | '/pdfs'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/suporte'
    | '/admin/gerar'
    | '/admin/questoes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/historico'
    | '/pdfs'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/suporte'
    | '/admin_/gerar'
    | '/admin_/questoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  HistoricoRoute: typeof HistoricoRoute
  PdfsRoute: typeof PdfsRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SuporteRoute: typeof SuporteRoute
  AdminGerarRoute: typeof AdminGerarRoute
  AdminQuestoesRoute: typeof AdminQuestoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfs': {
      id: '/pdfs'
      path: '/pdfs'
      fullPath: '/pdfs'
      preLoaderRoute: typeof PdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/gerar': {
      id: '/admin_/gerar'
      path: '/admin/gerar'
      fullPath: '/admin/gerar'
      preLoaderRoute: typeof AdminGerarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/questoes': {
      id: '/admin_/questoes'
      path: '/admin/questoes'
      fullPath: '/admin/questoes'
      preLoaderRoute: typeof AdminQuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  HistoricoRoute: HistoricoRoute,
  PdfsRoute: PdfsRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SuporteRoute: SuporteRoute,
  AdminGerarRoute: AdminGerarRoute,
  AdminQuestoesRoute: AdminQuestoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
