// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbifwbkkhjfjzjlwwzpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiaWZ3YmtraGpmanpqbHd3enBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0NTU4NjYsImV4cCI6MjEwMjAzMTg2Nn0.de_aOKkpEmbQB4-lOYSW8uW_HvpFlTU__kTx--PgrgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});